sudo: required
services:
  - docker

before_install:
  - docker build -t wahoo66/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wahoo66/react-test npm test -- --coverage

after_success:
  - docker build -t wahoo66/multi-client ./client
  - docker build -t wahoo66/multi-nginx ./nginx
  - docker build -t wahoo66/multi-server ./server
  - docker build -t wahoo66/multi-worker ./worker

  # login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to dockerhub
  - docker push wahoo66/multi-client
  - docker push wahoo66/multi-nginx
  - docker push wahoo66/multi-server
  - docker push wahoo66/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-508430781741"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
